# Generated by Django 3.2.4 on 2022-02-28 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Edu_Master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_Us',
            fields=[
                ('contactus_id', models.AutoField(primary_key=True, serialize=False)),
                ('contactus_name', models.CharField(default='', max_length=50)),
                ('contactus_phone', models.CharField(default='', max_length=20)),
                ('contactus_email', models.CharField(default='', max_length=100)),
                ('contactus_message', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Profile',
            fields=[
                ('Student_PK', models.AutoField(primary_key=True, serialize=False)),
                ('Student_ID', models.CharField(default='', max_length=100)),
                ('Student_Name', models.CharField(default='', max_length=200)),
                ('Student_Email', models.CharField(default='', max_length=200)),
                ('Student_Phone', models.CharField(default='', max_length=200)),
                ('Student_DOB', models.DateField()),
                ('Student_Address', models.CharField(default='', max_length=500)),
                ('Student_Status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Hold', 'Hold')], default='', max_length=20)),
                ('Student_Bio', models.CharField(default='', max_length=1000)),
                ('Student_Profile_Pic', models.ImageField(blank=True, null=True, upload_to='Edu_Master\\Student')),
                ('Student_Github', models.CharField(default='', max_length=200)),
                ('Student_Linkedin', models.CharField(default='', max_length=200)),
                ('Student_Twitter', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
