# Generated by Django 3.2.4 on 2022-03-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Edu_Master', '0002_contact_us_student_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('Event_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Event_Name', models.CharField(default='', max_length=100)),
                ('Event_Desc', models.CharField(default='', max_length=200)),
                ('Event_Date_Time', models.DateTimeField()),
                ('Event_Dept', models.CharField(default='', max_length=50)),
                ('Event_Dept_ID', models.CharField(default='', max_length=50)),
                ('Event_Link', models.CharField(default='', max_length=100)),
                ('Event_img', models.ImageField(blank=True, null=True, upload_to='Edu_Master\\Events')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='Registered_As',
            field=models.CharField(choices=[('Student', 'Student'), ('Teacher', 'Teacher'), ('Admin', 'Admin')], default='', max_length=20),
        ),
    ]
