# Generated by Django 3.2.4 on 2022-03-14 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Edu_Master', '0005_auto_20220313_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_profile',
            name='Student_User_PK',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Edu_Master.user'),
            preserve_default=False,
        ),
    ]
