# Generated by Django 3.2.4 on 2022-03-14 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Edu_Master', '0006_student_profile_student_user_pk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_profile',
            name='Student_User_PK',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
