# Generated by Django 3.2.4 on 2022-03-16 20:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Edu_Master', '0007_alter_student_profile_student_user_pk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='Event_img',
            new_name='Event_Banner',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='Event_Desc',
            new_name='Event_Short_Desc',
        ),
        migrations.RemoveField(
            model_name='events',
            name='Event_Date_Time',
        ),
        migrations.RemoveField(
            model_name='events',
            name='Event_Dept_ID',
        ),
        migrations.AddField(
            model_name='events',
            name='Event_Date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='Event_Long_desc',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='events',
            name='Event_Time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='Event_Topic',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='events',
            name='Event_Dept',
            field=models.CharField(choices=[('Java', 'Java'), ('Python', 'Python'), ('Auto Mobile', 'Auto Mobile')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='events',
            name='Event_Name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
