# Generated by Django 3.2.4 on 2022-03-16 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Edu_Master', '0008_auto_20220317_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='Event_Status',
            field=models.CharField(choices=[('Active', 'Active'), ('De-Active', 'De-Active')], default='', max_length=50),
        ),
    ]
