# Generated by Django 3.2.4 on 2022-03-31 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Edu_Master', '0014_events_event_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_profile',
            name='Student_ID',
            field=models.CharField(default='<django.db.models.fields.AutoField>', max_length=100),
        ),
        migrations.CreateModel(
            name='Event_Register',
            fields=[
                ('Event_Register_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Registration_Date', models.DateTimeField()),
                ('Event_ID', models.ManyToManyField(to='Edu_Master.Events')),
                ('Student_PK', models.ManyToManyField(to='Edu_Master.Student_Profile')),
            ],
        ),
    ]
