# Generated by Django 3.2.4 on 2022-03-31 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Edu_Master', '0015_auto_20220331_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_Detail',
            fields=[
                ('Course_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Course_Name', models.CharField(default='', max_length=100)),
                ('Start_Date', models.DateField()),
                ('End_Date', models.DateField()),
                ('Course_Trainer', models.CharField(default='', max_length=500)),
                ('Course_Desc', models.TextField(default='')),
                ('Course_Status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Hold', 'Hold')], default='', max_length=100)),
                ('CourseBanner', models.ImageField(blank=True, null=True, upload_to='Edu_Master\\Course')),
            ],
        ),
    ]
