# Generated by Django 3.2.4 on 2022-04-06 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Edu_Master', '0016_course_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher_Profile',
            fields=[
                ('Teacher_PK', models.AutoField(primary_key=True, serialize=False)),
                ('Teacher_ID', models.CharField(default='', max_length=100)),
                ('Teacher_Name', models.CharField(default='', max_length=200)),
                ('Teacher_Email', models.CharField(default='', max_length=200)),
                ('Teacher_Phone', models.CharField(default='', max_length=200)),
                ('Teacher_DOB', models.DateField()),
                ('Teacher_Address', models.CharField(default='', max_length=500)),
                ('Teacher_Status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Hold', 'Hold')], default='', max_length=20)),
                ('Teacher_Bio', models.CharField(default='', max_length=1000)),
                ('Teacher_Profile_Pic', models.ImageField(blank=True, null=True, upload_to='Edu_Master\\Teacher')),
                ('Teacher_Github', models.CharField(default='', max_length=200)),
                ('Teacher_Linkedin', models.CharField(default='', max_length=200)),
                ('Teacher_Twitter', models.CharField(default='', max_length=200)),
                ('Teacher_User_PK', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
