# Generated by Django 3.2.4 on 2022-04-06 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Edu_Master', '0017_teacher_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_profile',
            name='Teacher_Bio',
            field=models.CharField(default='None', max_length=1000),
        ),
        migrations.AlterField(
            model_name='teacher_profile',
            name='Teacher_Github',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='teacher_profile',
            name='Teacher_Linkedin',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='teacher_profile',
            name='Teacher_Twitter',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
