# Generated by Django 3.2.4 on 2022-04-06 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Edu_Master', '0018_auto_20220407_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_register',
            name='Registration_Date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
