# Generated by Django 3.2.4 on 2022-04-12 23:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Edu_Master', '0019_alter_event_register_registration_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_Profile',
            fields=[
                ('Admin_PK', models.AutoField(primary_key=True, serialize=False)),
                ('Admin_ID', models.CharField(default='', max_length=100)),
                ('Admin_Name', models.CharField(default='', max_length=200)),
                ('Admin_Email', models.CharField(default='', max_length=200)),
                ('Admin_Phone', models.CharField(default='', max_length=200)),
                ('Admin_DOB', models.DateField()),
                ('Admin_Address', models.CharField(default='', max_length=500)),
                ('Admin_Status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Hold', 'Hold')], default='', max_length=20)),
                ('Admin_Bio', models.CharField(default='None', max_length=1000)),
                ('Admin_Profile_Pic', models.ImageField(blank=True, null=True, upload_to='Edu_Master\\Admin')),
                ('Admin_Github', models.CharField(default='None', max_length=200)),
                ('Admin_Linkedin', models.CharField(default='None', max_length=200)),
                ('Admin_Twitter', models.CharField(default='None', max_length=200)),
                ('Admin_User_PK', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
