# Generated by Django 3.2.4 on 2022-04-13 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Edu_Master', '0020_admin_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_Time_Table',
            fields=[
                ('Course_Time_Table_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Class_Day', models.CharField(choices=[('SunDay', 'SunDay'), ('MonDay', 'MonDay'), ('TuesDay', 'TuesDay'), ('WednesDay', 'WednesDay'), ('ThursDay', 'ThursDay'), ('FriDay', 'FriDay'), ('SaturDay', 'SaturDay')], default='', max_length=100)),
                ('Class_Date', models.DateField()),
                ('Class_Start_Time', models.TimeField()),
                ('Class_End_Time', models.TimeField()),
                ('Class_Topic', models.CharField(default='', max_length=200)),
                ('Class_Link', models.CharField(default='', max_length=200)),
                ('Course_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Edu_Master.course_detail')),
            ],
        ),
        migrations.CreateModel(
            name='Course_Syllabus',
            fields=[
                ('Course_Syllabus_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Module_Name', models.CharField(default='', max_length=100)),
                ('Module_Week', models.CharField(default='', max_length=50)),
                ('Module_Topic', models.CharField(default='', max_length=200)),
                ('Module_Description', models.CharField(default='', max_length=1000)),
                ('Course_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Edu_Master.course_detail')),
            ],
        ),
        migrations.CreateModel(
            name='Course_Module',
            fields=[
                ('Course_Module_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Module_Topic', models.CharField(default='', max_length=200)),
                ('module_Content', models.FileField(upload_to='Edu_Master\\Course_Module')),
                ('Course_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Edu_Master.course_detail')),
            ],
        ),
    ]
