# Generated by Django 3.2.4 on 2022-04-13 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Edu_Master', '0021_course_module_course_syllabus_course_time_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_Exam_Table',
            fields=[
                ('Exam_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Exam_Name', models.CharField(default='', max_length=200)),
                ('Exam_Date', models.DateField()),
                ('Exam_Start_Time', models.TimeField()),
                ('Exam_End_Time', models.TimeField()),
                ('Exam_Link', models.CharField(default='', max_length=300)),
                ('Course_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Edu_Master.course_detail')),
            ],
        ),
    ]
