# Generated by Django 3.2.4 on 2022-04-13 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Edu_Master', '0022_course_exam_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course_exam_table',
            old_name='Course_ID',
            new_name='Course_Name',
        ),
        migrations.RenameField(
            model_name='course_module',
            old_name='Course_ID',
            new_name='Course_Name',
        ),
        migrations.RenameField(
            model_name='course_syllabus',
            old_name='Course_ID',
            new_name='Course_Name',
        ),
        migrations.RenameField(
            model_name='course_time_table',
            old_name='Course_ID',
            new_name='Course_Name',
        ),
    ]
