# Generated by Django 3.2.4 on 2022-04-13 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Edu_Master', '0023_auto_20220413_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_exam_table',
            name='Course_Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Edu_Master.course_detail'),
        ),
        migrations.AlterField(
            model_name='course_module',
            name='Course_Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Edu_Master.course_detail'),
        ),
        migrations.AlterField(
            model_name='course_syllabus',
            name='Course_Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Edu_Master.course_detail'),
        ),
        migrations.AlterField(
            model_name='course_time_table',
            name='Course_Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Edu_Master.course_detail'),
        ),
    ]
