# Generated by Django 4.0.4 on 2022-04-22 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Edu_Master', '0024_auto_20220413_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Registered_As',
            field=models.CharField(choices=[('None', 'None'), ('Student', 'Student'), ('Teacher', 'Teacher'), ('Admin', 'Admin'), ('LibraryAdmin', 'LibraryAdmin')], default='', max_length=20),
        ),
    ]
