# Generated by Django 4.0.4 on 2022-04-22 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Edu_Master', '0025_alter_user_registered_as'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('Book_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Book_Title', models.CharField(max_length=100)),
                ('Book_Author', models.CharField(max_length=100)),
                ('Book_Publish_Year', models.CharField(max_length=100)),
                ('Book_Publisher', models.CharField(max_length=200)),
                ('Book_ISBN', models.CharField(max_length=100)),
                ('Book_Edition', models.CharField(default='', max_length=100)),
                ('Book_Length', models.IntegerField()),
                ('Book_Desc', models.CharField(max_length=1000)),
                ('Audio_Start_Page', models.PositiveSmallIntegerField(default=0)),
                ('Book_Category', models.CharField(choices=[('Science', 'Science'), ('Life_Style', 'Life_Style'), ('Comp_Science', 'Comp_Science'), ('Communication', 'Communication'), ('Medicine', 'Medicine'), ('Eco_Fin', 'Eco_Fin')], default='', max_length=100)),
                ('Book_Genre', models.CharField(default='', max_length=1000)),
                ('Book_Uploaded_By', models.CharField(blank=True, max_length=100, null=True)),
                ('Book_User_Id', models.CharField(blank=True, max_length=100, null=True)),
                ('Book_Pdf', models.FileField(upload_to='Eduline\\Book_PDF')),
                ('Book_Cover', models.ImageField(blank=True, null=True, upload_to='Eduline\\Book_Cover')),
            ],
        ),
    ]
