# Generated by Django 4.0.4 on 2022-05-01 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Edu_Master', '0026_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='Book_Cover',
            field=models.ImageField(blank=True, null=True, upload_to='Edu_Master\\Book_Cover'),
        ),
        migrations.AlterField(
            model_name='books',
            name='Book_Pdf',
            field=models.FileField(upload_to='Edu_Master\\Book_PDF'),
        ),
        migrations.CreateModel(
            name='Student_Library_Profile',
            fields=[
                ('Library_PK', models.AutoField(primary_key=True, serialize=False)),
                ('Library_User_Profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Edu_Master.student_profile')),
            ],
        ),
    ]
