# Generated by Django 4.0.4 on 2022-05-06 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Edu_Master', '0029_student_library_profile_library_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Librarian_Profile',
            fields=[
                ('Librarian_PK', models.AutoField(primary_key=True, serialize=False)),
                ('Librarian_ID', models.CharField(default='', max_length=100)),
                ('Librarian_Name', models.CharField(default='', max_length=200)),
                ('Librarian_Email', models.CharField(default='', max_length=200)),
                ('Librarian_Phone', models.CharField(default='', max_length=200)),
                ('Librarian_DOB', models.DateField()),
                ('Librarian_Address', models.CharField(default='', max_length=500)),
                ('Librarian_Status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Hold', 'Hold')], default='', max_length=20)),
                ('Librarian_Bio', models.CharField(default='None', max_length=1000)),
                ('Librarian_Profile_Pic', models.ImageField(blank=True, null=True, upload_to='Edu_Master\\Librarian')),
                ('Librarian_Github', models.CharField(default='None', max_length=200)),
                ('Librarian_Linkedin', models.CharField(default='None', max_length=200)),
                ('Librarian_Twitter', models.CharField(default='None', max_length=200)),
                ('Librarian_User_PK', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
