# Generated by Django 4.0.4 on 2022-05-07 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Edu_Master', '0030_librarian_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_detail',
            name='Course_Skill',
            field=models.CharField(default='', max_length=200),
        ),
    ]
