# Generated by Django 4.0.4 on 2022-05-07 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Edu_Master', '0031_course_detail_course_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_detail',
            name='Course_level',
            field=models.CharField(choices=[('Introductory', 'Introductory'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='', max_length=20),
        ),
    ]
