# Generated by Django 4.0.4 on 2022-05-09 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Edu_Master', '0032_course_detail_course_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_detail',
            name='Course_Trainer',
        ),
        migrations.AddField(
            model_name='course_detail',
            name='Course_Instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Edu_Master.teacher_profile'),
        ),
    ]
