# Generated by Django 4.0.4 on 2022-05-09 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Edu_Master', '0034_course_detail_course_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_detail',
            name='Course_Rating',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
