# Generated by Django 4.0.4 on 2022-05-21 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Edu_Master', '0035_alter_course_detail_course_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact_Us',
        ),
    ]
