# Generated by Django 4.0.4 on 2022-05-21 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Edu_Master', '0036_delete_contact_us'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_us',
            fields=[
                ('Contact_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Contact_Name', models.CharField(default='None', max_length=200)),
                ('Contact_Email', models.EmailField(max_length=254)),
                ('Contact_Message', models.TextField(default='None')),
            ],
        ),
    ]
