# Generated by Django 4.0.4 on 2022-05-22 11:48

from django.db import migrations, models

from datetime import date
class Migration(migrations.Migration):

    dependencies = [
        ('Edu_Master', '0037_contact_us'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_DOB',
            field=models.DateField(default=date.today),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student_profile',
            name='Student_Address',
            field=models.CharField(default='None', max_length=500),
        ),
        migrations.AlterField(
            model_name='student_profile',
            name='Student_Bio',
            field=models.CharField(default='None', max_length=1000),
        ),
        migrations.AlterField(
            model_name='student_profile',
            name='Student_Github',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='student_profile',
            name='Student_ID',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='student_profile',
            name='Student_Linkedin',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='student_profile',
            name='Student_Phone',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='student_profile',
            name='Student_Twitter',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
