# Generated by Django 4.0.4 on 2022-05-22 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Edu_Master', '0038_user_user_dob_alter_student_profile_student_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_phone',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
