# Generated by Django 4.0.4 on 2022-06-20 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Edu_Master', '0041_book_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_request',
            name='Book_Request_Date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
