# Generated by Django 4.0.4 on 2022-06-20 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Edu_Master', '0043_book_request_book_request_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_request',
            name='Book_Request_By',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
