# Generated by Django 4.0.4 on 2022-06-21 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Edu_Master', '0045_alter_book_request_book_request_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_request',
            name='Book_Request_By',
        ),
    ]
