# Generated by Django 4.0.4 on 2022-06-21 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Edu_Master', '0046_remove_book_request_book_request_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_request',
            name='Book_Request_Date',
        ),
        migrations.AddField(
            model_name='book_request',
            name='Book_Request_By',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='Edu_Master.student_profile'),
            preserve_default=False,
        ),
    ]
