# Generated by Django 4.0.4 on 2022-06-21 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Edu_Master', '0047_remove_book_request_book_request_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book_Request',
        ),
    ]
