# Generated by Django 4.0.4 on 2022-06-22 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Edu_Master', '0050_alter_book_request_book_request_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_request',
            name='Book_Request_Status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Hold', 'Hold')], default='None', max_length=50),
        ),
    ]
