# Generated by Django 4.0.4 on 2022-07-12 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Edu_Master', '0052_teacher_profile_teacher_dept'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_detail',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
