# Generated by Django 4.0.4 on 2022-07-29 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Edu_Master', '0054_events_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address_Book',
            fields=[
                ('AB_ID', models.AutoField(primary_key=True, serialize=False)),
                ('AB_Party_Id', models.CharField(default='None', max_length=50)),
                ('AB_Party_Address', models.CharField(default='None', max_length=500)),
                ('AB_Party_City', models.CharField(default='None', max_length=200)),
                ('AB_Party_State', models.CharField(default='None', max_length=200)),
                ('AB_Party_Country', models.CharField(default='None', max_length=200)),
                ('AB_Party_Zip', models.CharField(default='None', max_length=200)),
            ],
        ),
    ]
