# Generated by Django 4.0.4 on 2022-08-14 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Edu_Master', '0056_contact_us_contact_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_us',
            name='Contact_Created_Date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='contact_us',
            name='Contact_Effective_End_Date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='contact_us',
            name='Contact_Last_Updated_Date',
            field=models.DateTimeField(null=True),
        ),
    ]
