# Generated by Django 4.0.4 on 2022-08-14 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Edu_Master', '0057_alter_contact_us_contact_created_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact_us',
        ),
    ]
