# Generated by Django 4.0.4 on 2022-09-02 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Edu_Master', '0063_teacher_profile_log_student_profile_log_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='librarian_profile_log',
            old_name='LPLog_Admin_PK',
            new_name='LPLog_Librarian_PK',
        ),
    ]
