# Generated by Django 4.0.4 on 2022-09-02 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Edu_Master', '0064_rename_lplog_admin_pk_librarian_profile_log_lplog_librarian_pk'),
    ]

    operations = [
        migrations.CreateModel(
            name='login_Log',
            fields=[
                ('LLog_PK', models.AutoField(primary_key=True, serialize=False)),
                ('LLog_Last_Login_Time', models.DateTimeField()),
                ('LLog_LogOut_Time', models.DateTimeField(blank=True, null=True)),
                ('LLog_Effective_End_Date', models.DateTimeField(blank=True, null=True)),
                ('LLog_User_PK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
