# Generated by Django 4.0.4 on 2022-09-06 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Edu_Master', '0065_login_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_syllabus',
            name='Module_Effective_End_Date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course_syllabus',
            name='Module_Last_Update_Date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course_syllabus',
            name='Module_Last_Updated_By',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
