# Generated by Django 4.0.4 on 2022-09-07 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Edu_Master', '0067_course_module_module_effective_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_time_table',
            name='Class_Effective_End_Date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course_time_table',
            name='Class_Last_Update_Time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course_time_table',
            name='Class_Last_Updated_By',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
