# Generated by Django 4.0.4 on 2022-09-07 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Edu_Master', '0068_course_time_table_class_effective_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_exam_table',
            name='Exam_Effective_End_Date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course_exam_table',
            name='Exam_Last_Update_Time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course_exam_table',
            name='Exam_Last_Updated_By',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
