# Generated by Django 4.0.4 on 2022-09-14 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Edu_Master', '0069_course_exam_table_exam_effective_end_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address_Book',
        ),
    ]
