# Generated by Django 4.0.4 on 2022-09-14 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Edu_Master', '0070_delete_address_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address_Book',
            fields=[
                ('AB_ID', models.AutoField(primary_key=True, serialize=False)),
                ('AB_Party_Type', models.CharField(choices=[('Student', 'Student'), ('Teacher', 'Teacher'), ('Admin', 'Admin'), ('Librarian', 'Librarian')], default='None', max_length=50)),
                ('AB_Party_Address', models.CharField(default='None', max_length=500)),
                ('AB_Party_City', models.CharField(default='None', max_length=200)),
                ('AB_Party_State', models.CharField(default='None', max_length=200)),
                ('AB_Party_Country', models.CharField(default='None', max_length=200)),
                ('AB_Last_Update_Date', models.DateTimeField(blank=True, null=True)),
                ('AB_Effective_End_Date', models.DateTimeField(blank=True, null=True)),
                ('AB_Party_Zip', models.CharField(default='None', max_length=200)),
                ('AB_Last_Updated_By', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Edu_Master.admin_profile')),
                ('AB_Party_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
