# Generated by Django 4.0.4 on 2022-09-14 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Edu_Master', '0071_address_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='address_book',
            name='AB_Party_phone',
            field=models.CharField(default='None', max_length=20),
        ),
    ]
