# Generated by Django 4.0.4 on 2022-09-14 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Edu_Master', '0072_address_book_ab_party_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address_book',
            name='AB_Party_Zip',
            field=models.CharField(default='None', max_length=20),
        ),
    ]
