# Generated by Django 4.0.4 on 2022-09-20 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Edu_Master', '0073_alter_address_book_ab_party_zip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address_book',
            name='AB_Party_Id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User_Address_Book', to=settings.AUTH_USER_MODEL),
        ),
    ]
