# Generated by Django 4.0.4 on 2022-09-20 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Edu_Master', '0074_alter_address_book_ab_party_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='Event_Level',
            field=models.CharField(choices=[('Student', 'Student'), ('Teacher', 'Teacher'), ('Librarian', 'Librarian'), ('Admin', 'Admin'), ('General', 'General')], default='General', max_length=50),
        ),
    ]
