# Generated by Django 4.0.4 on 2022-09-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Edu_Master', '0075_events_event_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='address_book',
            name='AB_Party_Email',
            field=models.CharField(default='None', max_length=250),
        ),
        migrations.AddField(
            model_name='address_book',
            name='AB_Party_Name',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
