# Generated by Django 4.0.4 on 2022-10-15 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Edu_Master', '0079_email_detail_email_attachment_email_detail_email_bcc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='email_detail',
            name='Email_Delivery_Status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Hold', 'Hold'), ('Not Delivered', 'Not Delivered')], default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='email_detail',
            name='Email_Submission_Type',
            field=models.CharField(choices=[('System Generated', 'System Generated'), ('Manual', 'Manual')], default='None', max_length=50),
        ),
    ]
