# Generated by Django 4.0.4 on 2022-10-15 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Edu_Master', '0080_email_detail_email_delivery_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email_detail',
            name='Email_Submission_Type',
            field=models.CharField(choices=[('Welcome Email', 'Welcome Email'), ('Account Activation', 'Account Activation'), ('Login Credential', 'Login Credential'), ('Manual Email', 'Manual Email'), ('General Email', 'General Email'), ('Profile Change', 'Profile Change')], default='None', max_length=50),
        ),
    ]
