# Generated by Django 4.0.4 on 2022-10-15 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Edu_Master', '0081_alter_email_detail_email_submission_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='email_detail',
            name='Email_Created_By',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='email_detail',
            name='Email_Last_Updated_By',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Edu_Master.admin_profile'),
        ),
    ]
