# Generated by Django 4.0.4 on 2022-11-25 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Edu_Master', '0082_email_detail_email_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_review',
            fields=[
                ('Review_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Review_Date', models.DateTimeField(blank=True, null=True)),
                ('Review_message', models.TextField(default='')),
                ('Review_Last_Updated_Date', models.DateTimeField(blank=True, null=True)),
                ('Review_Effective_End_Date', models.DateTimeField(blank=True, null=True)),
                ('Reviewed_Course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Edu_Master.course_detail')),
                ('Reviewer_Name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
