# Generated by Django 4.0.4 on 2022-12-02 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Edu_Master', '0083_course_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_review',
            name='Reviewer_Name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Edu_Master.student_profile'),
        ),
    ]
