# Generated by Django 4.0.4 on 2022-12-05 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Edu_Master', '0084_alter_course_review_reviewer_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='course_registratiobn',
            fields=[
                ('CR_ID', models.AutoField(primary_key=True, serialize=False)),
                ('CR_Status', models.CharField(choices=[('Active', 'Active'), ('De-active', 'De-active'), ('Hold', 'Hold')], default='None', max_length=100)),
                ('CR_DateTime', models.DateTimeField(blank=True, null=True)),
                ('CR_Last_Updated_Date', models.DateTimeField(blank=True, null=True)),
                ('CR_Effective_End_Date', models.DateTimeField(blank=True, null=True)),
                ('CR_Course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Edu_Master.course_detail')),
                ('CR_Last_Updated_By', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('CR_Student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Edu_Master.student_profile')),
            ],
        ),
    ]
