# Generated by Django 4.0.4 on 2022-12-05 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Edu_Master', '0085_course_registratiobn'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='course_registratiobn',
            new_name='course_registration',
        ),
    ]
