# Generated by Django 4.0.4 on 2022-12-07 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Edu_Master', '0086_rename_course_registratiobn_course_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_review',
            name='Review_Status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Hold', 'Hold')], default='None', max_length=100),
        ),
    ]
