# Generated by Django 4.0.4 on 2022-12-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Edu_Master', '0087_course_review_review_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_registration',
            name='CR_End_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course_registration',
            name='CR_Start_Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
