# Generated by Django 4.0.4 on 2022-12-22 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Edu_Master', '0088_course_registration_cr_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_time_table',
            name='Class_Day',
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('Blog_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Blog_Title', models.CharField(default='None', max_length=200)),
                ('Blog_DateTime', models.DateTimeField(blank=True, null=True)),
                ('Blog_Description', models.TextField(default='')),
                ('Blog_Banner', models.FileField(blank=True, null=True, upload_to='Edu_Master\\Blog')),
                ('Blog_Status', models.CharField(choices=[('Active', 'Active'), ('De-active', 'De-active'), ('Hold', 'Hold')], default='None', max_length=50)),
                ('Blog_Last_Update_Date', models.DateTimeField(blank=True, null=True)),
                ('Blog_Effective_End_Date', models.DateTimeField(blank=True, null=True)),
                ('Blog_Last_Updated_By', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Edu_Master.admin_profile')),
                ('Blog_writer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
