# Generated by Django 4.0.4 on 2022-12-29 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Edu_Master', '0089_remove_course_time_table_class_day_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_Review',
            fields=[
                ('Review_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Review_Date', models.DateTimeField(blank=True, null=True)),
                ('Review_message', models.TextField(default='')),
                ('Review_Status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Hold', 'Hold')], default='None', max_length=100)),
                ('Review_Last_Updated_Date', models.DateTimeField(blank=True, null=True)),
                ('Review_Effective_End_Date', models.DateTimeField(blank=True, null=True)),
                ('Reviewed_Blog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Edu_Master.blog')),
                ('Reviewer_Name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Edu_Master.student_profile')),
            ],
        ),
    ]
