# Generated by Django 4.0.4 on 2023-02-15 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Edu_Master', '0092_alter_blog_blog_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='Blog_Active_Status',
            field=models.BooleanField(default=False),
        ),
    ]
