# Generated by Django 4.0.4 on 2023-02-22 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Edu_Master', '0093_blog_blog_active_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_live_status',
            field=models.BooleanField(default=False),
        ),
    ]
