# Generated by Django 4.0.4 on 2023-02-24 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Edu_Master', '0094_user_user_live_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_time_table',
            name='Class_Date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
