# Generated by Django 4.0.4 on 2023-07-19 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Edu_Master', '0095_alter_course_time_table_class_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Feedback',
            fields=[
                ('Feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('Feedback_Text', models.TextField(default='')),
                ('Feedback_attachment', models.FileField(upload_to='Edu_Master\\Feedback')),
                ('Feedback_Date', models.DateTimeField(blank=True, null=True)),
                ('Feedback_staus', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Hold', 'Hold')], default='None', max_length=100)),
                ('Feedback_Updated_Date', models.DateTimeField(blank=True, null=True)),
                ('Feedback_Effective_End_Date', models.DateTimeField(blank=True, null=True)),
                ('Feedback_Updated_By', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
