# Generated by Django 4.0.4 on 2023-08-18 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Edu_Master', '0097_alter_user_feedback_feedback_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='slug',
            field=models.SlugField(default='', null=True),
        ),
    ]
