# Generated by Django 4.0.4 on 2024-04-22 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Edu_Master', '0100_address_book_slug_admin_profile_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_module',
            name='module_Banner',
            field=models.FileField(blank=True, null=True, upload_to='Edu_Master\\Course_Module_Banner'),
        ),
    ]
