# Generated by Django 4.0.4 on 2024-04-22 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Edu_Master', '0101_course_module_module_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='address_book',
            name='module_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Hold', 'Hold')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='course_exam_table',
            name='module_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Hold', 'Hold')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='course_module',
            name='module_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Hold', 'Hold')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='course_syllabus',
            name='Module_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Hold', 'Hold')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='course_time_table',
            name='module_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Hold', 'Hold')], default='', max_length=100),
        ),
    ]
